POST http://localhost:3000/campaigns

{
    "name": "Campaign 1",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec.",
    "emails": [
        "teste@teste.com"
    ]
}
###
GET http://localhost:3000/campaigns
